version: '3.8'
services:
  clients:
    build:
      context: ./client-service
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - demo-bank-network

  core:
    build:
      context: ./core-service
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - demo-bank-network

networks:
  demo-bank-network:
    driver: bridge
