server:
  port: 8001
spring:
  webflux:
    base-path: /demobank/api/client
  application:
    name: clients
  r2dbc:
    properties:
      schema: demobank
    url: r2dbc:postgresql://localhost:5432/demoBank
    username: postgres
    password: password
    initialization-mode: always

#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters


