server:
  port: 8000
spring:
  webflux:
    base-path: /demobank/api/core
  application:
    name: core
  r2dbc:
    properties:
      schema: demobank
    url: r2dbc:postgresql://localhost:5432/demoBank
    username: postgres
    password: password
    initialization-mode: always

api:
  client:
    url: http://clients:8001/demobank/api/client

#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters


